#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend lb
    bind *:80\
    mode http
    default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 911-web-01 34.74.39.127:80 check
    server 911-web-02 35.196.159.36:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
