#!/usr/bin/env bash
# configures the container to fit the requirements
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
